name: Get All Changed Files
description: Get all of the files changed/modified in a pull request or push's commits.
author: Meyisoft OU, Inc.
branding:
  icon: join_inner
  color: blue
runs:
  using: node12
  main: dist/index.js
inputs:
  token:
    description: >
      GitHub token for GitHub API requests.
      Users shouldn't need to set this themselves.
    required: true
    default: ${{ github.token }}
  regex:
    description: >
      String regular expression to compare against the full paths of the commit file list
    required: true
    default: .
outputs:
  match:
    description: >
      boolean indicating if any filepath math the regular expression provided  
